version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/rails
hooks:
  BeforeInstall:
    - location: beforeInstall.sh
      runas: root
  ApplicationStart:
    - location: applicationStart.sh
      runas: root
#   ApplicationStop:
#     - location: scripts/applicationStop.sh
#       runas: root
