version: 0.0
os: linux
files:
#   - source: /config.ru
#     destination: /home/ubuntu/rails
#     overwrite: true
    
#   - source: /Gemfile
#     destination: /home/ubuntu/rails
#     overwrite: true
    
#   - source: /Gemfile.lock
#     destination: /home/ubuntu/rails
#     overwrite: true
    
#   - source: /Rakefile
#     destination: /home/ubuntu/rails
#     overwrite: true
    
#   - source: /README.md
#     destination: /home/ubuntu/rails
#     overwrite: true
    
#   - source: /app/
#     destination: /home/ubuntu/rails
#     overwrite: true
    
#   - source: /config/
#     destination: /home/ubuntu/rails
#     overwrite: true
    
#   - source: /lib/
#     destination: /home/ubuntu/rails
#     overwrite: true
    
#   - source: /log/
#     destination: /home/ubuntu/rails
#     overwrite: true
    
#   - source: /vendor/
#     destination: /home/ubuntu/rails
#     overwrite: true
    
#   - source: /
#     destination: /home/ubuntu/rails
#     overwrite: true
    
permissions:
  - object: /home/ubuntu/rails
    owner: root
    group: root
    mode: 777
    
hooks:
  BeforeInstall:
    - location: beforeInstall.sh
      runas: root
  ApplicationStart:
    - location: applicationStart.sh
      runas: root
#   ApplicationStop:
#     - location: scripts/applicationStop.sh
#       runas: root


