version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: beforeInstall.sh
      runas: root
      
# phases:
#   install:
#     commands:
#       - echo "remove old files"
#       - rm -rf /home/ubuntu/rails
#       - echo "cloning New files using github repo"
#       - git clone https://github.com/JD4912/test_project.git /home/ubuntu/rails
#       - echo "change the working directory and delete Gemfile.lock"
#       - sudo cd /home/ubuntu/rails && rm Gemfile.lock\
#       - echo "Install the budle package"
#       - bundle install
#       - echo "Run the Rails server"
#       - rails server -b 0.0.0.0
      
