version: 0.0
os: linux
files:
#   - source: /
#     destination: /home/ubuntu/rails
       
permissions:
  - object: /home/ubuntu/rails
    owner: root
    group: root
    mode: 777
    
hooks:
  BeforeInstall:
    - location: beforeInstall.sh
      runas: root
#   ApplicationStart:
#     - location: applicationStart.sh
#       runas: root
#   ApplicationStop:
#     - location: scripts/applicationStop.sh
#       runas: root


