#!/bin/bash
sudo su -
rm -rf /ruby
git clone https://github.com/JD4912/test_project.git /ruby
cd /ruby 
rm -rf Gemfile.lock
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
curl -L get.rvm.io | bash -s stable
source /etc/profile.d/rvm.sh
rvm requirements
rvm install 2.7.1
gem install rails
bundle install 


